apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployer
rules:
- apiGroups: ["*"]
  resources: ["namespaces"]
  verbs: ["create"]
- apiGroups: ["*"]
  resources: ["services"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["ingresses"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: deployer-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployer
subjects:
- kind: ServiceAccount
  name: deployer
  namespace: kube-system
