language: minimal
# Needed for docker
sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
script:
  - ./build.sh
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    ./push.sh
    fi